# This is the entry point for the AI terminal assistant program.  It outlines the main program flow and calls other files at a high level.

import argparse
import sys
import traceback
from importlib.metadata import version, PackageNotFoundError

from . import apiHandler
from . import userInterface
from . import chatBot
from . import configHandler
from . import riskAssessment


def get_version():
    try:
        return version("gptautocli")
    except PackageNotFoundError:
        return "unknown"


def parse_args():
    """Parse command line arguments for gptautocli"""
    parser = argparse.ArgumentParser(
        description="gptautocli - Provides a conversational interface to the terminal, allowing users to run commands and perform tasks using natural language.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    gptautocli                            # Start a new chat with default settings
    gptautocli -m your-model-name         # Start a new chat with the model of your choice (e.g. gpt-4, gpt-3.5-turbo, etc.)
    gptautocli --risk-level 3             # Set the risk tolerance to 3
    gptautocli -h                         # Display this help message
    gptautocli -v                         # Display the version number
        """)

    parser.add_argument("-v", "--version", action="store_true", help="Display the version number")
    parser.add_argument("-m", "--model", type=str, help="Specify the model to use for the chat")
    parser.add_argument("-r", "--risk-level", type=int, help="Specify the risk tolerance level for commands generated by the AI")
    return parser.parse_args()


def main():
    """Main program flow"""
    args = parse_args()
    if args.version:
        print(f"gptautocli version {get_version()}")
        sys.exit()

    model_name = args.model if args.model else "gpt-5.4-mini"
    risk_level = args.risk_level if args.risk_level is not None else -1

    user_interface = userInterface.UserInterface()
    configHandler.ConfigHandler(user_interface)
    api_handler = apiHandler.ApiHandler(user_interface)

    riskAssessmentTool = riskAssessment.RiskAssessment(user_interface, api_handler, risk_level)
    risk_level = riskAssessmentTool.risk_tolerance
    user_interface.welcome(model_name, risk_level)

    agent_manager = chatBot.ChatBot(user_interface, api_handler, riskAssessmentTool, model_name, [])

    agent_manager.conversation_loop()
    agent_manager.shell.close()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print("\nExiting.")
    except Exception:
        traceback.print_exc()
        input("Press enter to exit.")
